version: "3.8"

services:
  app:
    build: .
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app

  redis_worker:
    build: .
    ports:
      - "5678:5678"
    command: python redis_worker.py
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  redis:
    image: redis:7.2
    ports:
      - "63799:${REDIS_PORT}"
    command: redis-server --requirepass $REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}